version: '3.1'
services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: filmotekajs
    container_name: nodejs
    ports:
      - "127.0.0.1:3000:3000"
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: filmoteka
    volumes:
      - ./db/postgres:/var/lib/postgresql:rw
    ports:
      - "127.0.0.1:5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@test.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
